run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: axelsvensson.com/mattermost-plugin-character-profiles
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
        disabled: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - text: "ST1003:"
      linters:
        - stylecheck
    - path: server/configuration.go
      linters:
        - unused
    - path: _test\.go
      linters:
        - bodyclose
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
